### ISSUE TITLE
The breeding doesn't work

### ISSUE THREAD

**Issue by nuka83** [JayZX535/wildcraft#10]
Hi, 
When I tamed a wolf ( Male and female), I give them cooked potatos like in the description.. but my wolf dont move... nothing it's happening. I have try many times and the same result. 
Can you help me please ( sorry for my bad english )

**Comment by JayZX535** [comment]
Did you make sure to click each wolf twice to put them in wander mode? (not sitting/following you)?

**Comment by nuka83** [comment]
thank you i'M stupid.... thank you so much

**Comment by JayZX535** [comment]
No problem!  Glad you got it sorted :)
