### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by scalda** [JayZX535/wildcraft#14]
on server load, it crashed [pastebin](https://pastebin.com/Tm3B68bt)

**Comment by JayZX535** [comment]
WildCraft is known to not run on servers as per issue #5 , but it's very helpful to have an actual log for this!  Gives me a starting place for server debugging.
That said, I'm gonna close this issue and move further discussion to the main thread (5).  In the future, please remember to check to see if your bug has already been reported before making a new issue ;)
